### ISSUE TITLE
TODO: Implement tree traversing api. 

### ISSUE THREAD

**Issue by Hrabal** [Hrabal/TemPy#11]
Implement a traversal method(s) to provide depth-first and breadth-first traversing paths on the tree starting from a chosen node:

    # Given this graph/tree:
    a = Div()
    b = Div()
    c = Span()
    d = Div()
    a(b(d), c)

         > c
    a -|
         > b -> d

    
    a.dft(order=tempy.PREORDER)
    >>> a, b, d, c
    a.dft(order=tempy.INORDER)
    >>> d, b, a, c
    a.dft(order=tempy.POSTORDER)
    >>> d, b, c, a
    a.bft()
    >>> a, b, c, d

Resources:

- [Math theory](https://jeremykun.com/2013/01/22/depth-and-breadth-first-search/) (don't be scared! ;) )
- [Wikipedia tree traversal](https://en.wikipedia.org/wiki/Tree_traversal)
- [Wikipedia depth first](https://en.wikipedia.org/wiki/Depth-first_search)
- [Wikipedia breadth-first](https://en.wikipedia.org/wiki/Breadth-first_search)
- [Good recipe example](http://code.activestate.com/recipes/579138-simple-breadth-first-depth-first-tree-traversal/)
- [a blog post](http://eddmann.com/posts/depth-first-search-and-breadth-first-search-in-python/)

**Comment by antoniomdk** [comment]
For inorder traversal, what should I take as left and right children?

**Comment by Hrabal** [comment]
I'd follow self.childs order. First added children (0 index) will be left-most, last added children (-1 index) will be right-most.
In this way, depth-first will always start traversal from the top of the DOM.

It would be nice to have a parameter for that. Default can be traversing the DOM top->down, `reverse` parameter make traversing go down-top.

**Comment by antoniomdk** [comment]
But when an object has more than two children should I split the list in two parts? o take the first as left child and the rest of the list as right children?

**Comment by Hrabal** [comment]
Oh now I see what you mean.
The most common python graph module, network-x, [does not](https://networkx.github.io/documentation/networkx-1.10/reference/algorithms.traversal.html) implement Depth-First In-order algorithm, and I guess it's because there is no right answer to your question. The [algorithm](http://www.ics.uci.edu/~eppstein/PADS/DFS.py) network-x is based on does not either.

I'd say to not implement INORDER traversal.

**Comment by antoniomdk** [comment]
I've already implemented it. Assuming first child is left and the rest is right. Should I remove that part?

**Comment by Hrabal** [comment]
I'll check if there is a standard on this when a node have more than 2 children. Since after the first child the father is visited again for the first time, that seems the most reasonable solution.

Anyway usually depth-first is used in pre and post order so I merged your commits and opened another issue for the future.

Thanks!
