### ISSUE TITLE
PrettyPrinting refactor

### ISSUE THREAD

**Issue by Hrabal** [Hrabal/TemPy#13]
Currently implemented pretty printing is bad, really bad.

`.render(pretty=True)` should produce an indented html string,, no idea if there is a standard for that.

**Comment by thakkardharmik** [comment]
@Hrabal I would like to give it a try. Please guide me on how can I contribute to the project.

**Comment by Hrabal** [comment]
Hi @thakkardharmik , I added you as collaborator.
This issue is basically a refactor of the pretty printing mechanism in the `.render()` methods in the `Content` and `Tag` classes.
I implemented it when those methods where recursive, but now they aren't so it doesn't work anymore.

When the pretty param is True, every closing tag should be followed by a newline, and every opening tag should be preceded by a number of tabs equal to the number of parents of the tag itself.

This is just a rule of thumb, if you find a way to make it prettier... well.. good! 😄 

To contribute just make your own branch (or fork the repo), develop and make a PR.
Please write few tests, I'll help too with tests since those should not be blocking.
