### ISSUE TITLE
ALWAYS OPEN: docstring correction and enanchemnt.

### ISSUE THREAD

**Issue by Hrabal** [Hrabal/TemPy#15]
Not a native english speaker so I'm sure my docstrings are not correct nor clear.

**Comment by tirthparikh** [comment]
Hi @Hrabal , This is my first time attempting to OS contribution. While I was reading the documentation, I found some errors to start with. I need your help in starting and understanding this project. I am also a python enthusiasts, but I like to start with the documentation first and then move on to the core project development. Thanks!

**Comment by Hrabal** [comment]
Hi @tirthparikh, thanks for helping out!
First of all, do you mean the full documentation @ [hrabal.github.io/TemPy-docs](hrabal.github.io/TemPy-docs)? If so, please fork, commit and make a pull request in this repository: [https://github.com/Hrabal/TemPy-docs](https://github.com/Hrabal/TemPy-docs).

Let me know every question you have, here, in the [Slack](https://tempy-dev.slack.com/) account (just ask for an invitation and I'll grant asap) or by email (look at [CONTRIBUTING.md](https://github.com/Hrabal/TemPy/blob/master/CONTRIBUTING.md) to find my email.

**Comment by tirthparikh** [comment]
Thanks for getting back! Yes, I was talking about https://github.com/Hrabal/TemPy-docs, I will fork the commit and make a pull request. 

I would be glad to join you on Slack, can you send me an invitation to parikht13 @ gmail . com
