### ISSUE TITLE
ALWAYS OPEN: documentation.

### ISSUE THREAD

**Issue by Hrabal** [Hrabal/TemPy#16]
Any contribution to this project documentation is welcomed.
Please read [the docs](https://hrabal.github.io/TemPy/), if you find typos errors (i'm not native speaker) please commit on the gh-pages branch of this [repo](https://github.com/Hrabal/TemPy/tree/gh-pages) and correct me/add new docs, then make a pull request.

**Comment by dpalmquist84** [comment]
Hrabal, I'd love to help you with this.

**Comment by Hrabal** [comment]
Hey @dpalmquist84 , really appreciated!
As you can see my english is "almost-close-to-ok", so I really need some help on the docs. Plus, I think I take for granted some features/methods that are not so really thank you!

I switched all the docs to the gh-pages branch, so It can be published to [https://hrabal.github.io/TemPy/](https://hrabal.github.io/TemPy/) via GitHub pages.
Let me know if you need some infos/anything.

**Comment by dpalmquist84** [comment]
Hrabal,

I'm happy to help.  I look at the readme first just to make sure it makes
sense to me.

Thanks,
David

**Comment by kinstalinist** [comment]
I definitely noticed a few little spelling and grammar errors throughout the comments and documentation. I'm pretty good at copyediting; I'd love to help! 😃

**Comment by Diablo2050** [comment]
Found a grammar error and would love to help fix it.

**Comment by Hrabal** [comment]
Thanks @Diablo2050

**Comment by verascity** [comment]
Hi! I'm going through the docs now. There are a few things I plan on fixing, but I also wanted to ask about this:

> from tempy.tags import *

Is there a reason to do it this way and not `import tempy.tags`?

**Comment by Hrabal** [comment]
Hi @verascity! 
The reason for the star import is to load in your module's namespace all the tags available to use,  instead the `import tempy.tags` statement will only load the "tempy" name.

If you check your `locals()` with `dir()` after the import you can see the difference:
```
>>> import tempy.tags
>>> dir()
['__annotations__', '__builtins__', '__doc__', '__loader__', '__name__', '__package__', '__spec__', 'tempy']
```
```
>>> from tempy.tags import *
>>> dir()
['A', 'Abbr', 'Acronym', 'Address', 'Applet', 'Area', 'Article', 'Aside', 'Audio', 'B', 'Base', 'Basefont', 'Bdi', 'Bdo', 'Big', 'Blockquote', 'Body', 'Br', 'Button', 'Canvas', 'Caption', 'Center', 'Cite', 'Code', 'Colgroup', 'Comment', 'Content', 'DOCTYPES', 'Datalist', 'Dd', 'Del', 'Details', 'Dfn', 'Dialog', 'Dir', 'Div', 'Dl', 'Doctype', 'Dt', 'Em', 'Embed', 'Fieldset', 'Figcaption', 'Figure', 'Font', 'Footer', 'Form', 'Frame', 'Frameset', 'H1', 'H2', 'H3', 'H4', 'H5', 'H6', 'Head', 'Header', 'Hr', 'Html', 'I', 'Iframe', 'Img', 'Input', 'Ins', 'Kbd', 'Keygen', 'Label', 'Legend', 'Li', 'Link', 'Main', 'Map', 'Mark', 'Menu', 'Menuitem', 'Meta', 'Meter', 'Nav', 'Noframes', 'Noscript', 'Object', 'Ol', 'Optgroup', 'Option', 'Output', 'P', 'Param', 'Picture', 'Pre', 'Progress', 'Q', 'Rp', 'Rt', 'Ruby', 'S', 'Samp', 'Script', 'Section', 'Select', 'Small', 'Source', 'Span', 'Strike', 'Strong', 'Style', 'Sub', 'Summary', 'Sup', 'Table', 'Tag', 'Tbody', 'Td', 'Textarea', 'Tfoot', 'Th', 'Thead', 'Time', 'Title', 'Tr', 'Track', 'Tt', 'U', 'Ul', 'Var', 'Video', 'VoidTag', 'Wbr', '__annotations__', '__builtins__', '__doc__', '__loader__', '__name__', '__package__', '__spec__', 'tag', 'tag_cls', 'tag_cls_name', 'tag_parent_cls', 'tags']
```
The star import is not recommended in common Python and is seen as "not Pythonic" for it loads a lot of unused objects, the optimal way to used the tags would be:

```
>>> from tempy import tags
>>> tags.Div()
<tempy.tags.Div 139143433775032803449285107515398214285.>
>>> # Now the namespace is less polluted:
>>> dir()
['__annotations__', '__builtins__', '__doc__', '__loader__', '__name__', '__package__', '__spec__', 'tags']
```



P.S: I just noticed that `tempy.tags` module leave a bit of dirt after the import: `'tag', 'tag_cls', 'tag_cls_name', 'tag_parent_cls', 'tags'` are not necessary and should not be accessible after the import, I opened the issue #66 on that if someone want to fix this.

**Comment by verascity** [comment]
D'oh -- what I actually meant was why not do `from tempy import tags`. My bad. With a relatively large import, isn't there a risk of conflict with variable names and other modules with the star import?

**Comment by Hrabal** [comment]
It's not in the docs because I'm lazy ;)
If you want to change that imports in the docs thank you! Both `from tempy.tags import <explicit list of used tags>` and `from tempy import tags` are reccomended ways to use TemPy.

**Comment by wwintermute** [comment]
Howdy, I corrected some spelling/grammar in the README.md but now see a lot of complaints from some maintainers about 'spam' grammer corrections during this years Hacktoberfest. Since corrections were specifically asked for in this issue is [this PR](https://github.com/Hrabal/TemPy/pull/87) okay?

**Comment by Hrabal** [comment]
Hi @wwintermute , I merged your PR.

**Comment by bradagy** [comment]
I'll see if I can help with correction of spelling/grammar.
