### ISSUE TITLE
ALWAYS OPEN: add examples.

### ISSUE THREAD

**Issue by Hrabal** [Hrabal/TemPy#17]
Add Tempy usage examples in the examples directory.

Ideally examples will contain a file for every TemPy usage and feature, plus a complete flask/weppy/whatever webapp made using TemPy.

**Comment by Chiouonthis** [comment]
Can I update the view for ```/``` so that it can link to the other examples? 

As of now it simply says, ```Ready for some Tempy examples?```, but it would be nice to have links to those examples right there.

**Comment by maalbano** [comment]
Hi ! I'd like to contribute an example using chart JS.

**Comment by Hrabal** [comment]
Hi @maalbano yes thanks! Please make a pull request with your additions.

**Comment by maalbano** [comment]
pull request here:  #106
