### ISSUE TITLE
.pop method should accepts named attributes.

### ISSUE THREAD

**Issue by Hrabal** [Hrabal/TemPy#19]
DOMElement.pop() method should accepts strings (or iterators of strings) as args.
If a string or an iterator of strings is provided, pop will perform removal of those named childs.
If no child with that name is found, and exception is raised.

    a = Div()(foo=Div(), this=A(href='/this')('This'), bar=Div())
    a.pop('this')

In this example `a.childs` should return `foo` and `bar`, `this` is removed from `a`

**Comment by antoniomdk** [comment]
Hey, I would like to work on this.

**Comment by Hrabal** [comment]
hey @antoniomdk, thanks for your help!
I added you to the collaborators so I can assign you this issue, you should've got a mail from GitHub to confirm.

Here for any question!

**Comment by antoniomdk** [comment]
Confirmed. Please, invite me to the slack channel. Thanks!

**Comment by antoniomdk** [comment]
Hey, What kind of Exception should the method throw? and the parameter idx is still used?

**Comment by Hrabal** [comment]
That's what I was thinking:
* a subclass of `TagError` and `KeyError` when popping a named attribute, a subclass of `TagError` and `IndexError` when popping by index.
* I'd replace idx with args, maintaining the fallback that if pop is called with no parameters the last child is popped.
* by design every DOM manipulation method should return either the DOMElement itself or 
 the resulting DOMElement, in this case I'd go with a list of the popped elements for forward-compatibility (I'm planning make a TemPyContainer class as a default for the each api return)

Any suggestion is welcome! ;)
