### ISSUE TITLE
 The benchmarks should be only about HTML generation and writing

### ISSUE THREAD

**Issue by Vesuvium** [Hrabal/TemPy#2]
Having benchmarks is great, but the current ones are not useful. TemPy is a templating engine, so what matters is how fast can TemPy generate and write html.
With wrk + flask you are accounting also for requests and flask performance. 

Why this? Because the likely use of TemPy is either in applications generating HTML once (static website generators, for example) or applications that generate HTML based on an HTTP request (django-like, for example).

In the first case, no HTTP is involved. In the second case, we can assume that a sensible django-like app would have some caching and hence a limited need for run-time generation of HTML.

**Comment by Hrabal** [comment]
I added benchmarks to compare TemPy to others templating engines (specifically Jinja2), and it seems that Flask (the one I always used) do some kind of work when rendering a Jinja2 template, so I decided to make a common small server for comparison so the other code is the same.

You think I can just measure 
````
from jinja2 import Template
with open('template.html') as f:
    Template(f.read()).render_template()
````
vs
````
from some_package import tempy_template
tempy_template.render()
````
?

**Comment by Vesuvium** [comment]
Yes, that's what I meant

**Comment by Hrabal** [comment]
Added benchmarks for template rendering only (no web serving):
https://github.com/Hrabal/TemPy/commit/4538cb6f15613c1ef34b97f3d8332ca60b13f4ab
