### ISSUE TITLE
Use metaprogramming to generate any tag.

### ISSUE THREAD

**Issue by antoniomdk** [Hrabal/TemPy#25]
I would be nice to use metaprogramming for generate any tag name without type it explicitly. I've found an example in Ruby, but I suppose it's applicable in python.
https://www.leighhalliday.com/creating-ruby-dsl

**Comment by Hrabal** [comment]
You mean to replicate this syntax?
```ruby
output = FancyMarkup.new.document do
  body do
    div id: "container" do
      ul class: "pretty" do
        li "Item 1", class: :active
        li "Item 2"
      end
    end
  end
end
```
or you mean to remove tags.py and dynamically generate them?

**Comment by antoniomdk** [comment]
I mean generate the content of tags.py dynamically but the same syntax of Div(Div()...
Not only for known tags but also for custom tags.

**Comment by Hrabal** [comment]
I don't think it's possible to do something like this for it will always raise a NameError.
```python
from tempy.tags import *
Div()(
      CustomNeverDeclaredTag()
)
```

One Idea would be to make a god object (like javascript's "$") that behaves as a class factory, so  it's possible to do something like:

```python
from tempy import T
Div()(
      T.CustomNeverDeclaredClass()
)
```
This is not hard to implement.

**Comment by antoniomdk** [comment]
Yes, If the class is not declared it will raise the error. But the second option could be great to implement. In the receiver of "missing methods" the new class content is the lowercase name. And it inherits from Tag.

**Comment by Hrabal** [comment]
Uhm yeah it can be useful. It's certainly easier to use custom tags with no special methods/properties/behaviors this way, and not define a class for a maybe one-time only custom tag.

I'll add that in the todo list.

**Comment by Hrabal** [comment]
I created [this issue](https://github.com/Hrabal/TemPy/issues/26) as a container of other god-object moethods Ideas.

**Comment by Hrabal** [comment]
I implemented in a [separate branch](https://github.com/Hrabal/TemPy/tree/T_god_object) a T object that works as a Tempy class factory. I also added a T.Void subclass to build void Tempy tags.

Before merging in master I'd like to add more features to the T objects. Other T object ides will be discussede in the [other issue](https://github.com/Hrabal/TemPy/issues/26), I'll close this one .
