### ISSUE TITLE
tempy.elements.Css - init should accept a dict with TemPy Tags as keys

### ISSUE THREAD

**Issue by Hrabal** [Hrabal/TemPy#33]
Now the init dict have this form:
```
{'html': {
            'body': {
                'color': 'red',
                'div': {
                    'color': 'green',
                    'border': '1px'
                }
            }
        },
        '#myid': {'color': 'blue'}
    }
}
```
Instead of (only) strings, the init should manage a dict with tempy.tags or tempy.widgets classes and instances as keys.

Example:
```
from tempy.tags import Div, A
link = A()
{'html': {
            'body': {
                'color': 'red',
                Div: {
                    'color': 'green',
                    'border': '1px'
                },
               link: {'color': 'yellow'}
            }
        },
        '#myid': {'color': 'blue'}
    }
}
```
Proposed implementation:
 - the `Div` class found in the dict will be translated into the `div` tag css selector
 - the `link` instance would be translated in the most defining possible way:
   - with his id, if it have one
   - with his css class(ses) if it have one or more
   -  with his tag name as the last fallback.

**Comment by MatthijsReyers** [comment]
Hi, I'd like try to have a go at implementing this.

**Comment by Hrabal** [comment]
Hi @MatthijsReyers, I assigned you the issue if you have any question just ask (I might be offline for the next few days, I'll reply as soon as I can!)

**Comment by MatthijsReyers** [comment]
Hi @Hrabal, it seems that when the init dict is filled with a `Div` or other Tag class, the current code already translates this to its tag in this line in `elements.py`:
```python
elif inspect.isclass(parent):
     result.append(
          getattr(parent, "_" + parent.__name__ + "__tag") + " "
     )
```
As for the behavior for instances of a Tag class, I have currently set it up in such a way that when the instance has multiple classes (and no ID obviously), the code generates a CSS selector for the element that has all of those classes.

Example, because code often means more than words:
```python
from tempy.elements import Css
from tempy.tags import Html, Head, Body, Meta, Link, Div, P, A, Style

test0 = A()
test1 = Div(id="cool")
test2 = P(klass="class1 class2 class3")

page = Html()(
    Head()(
        Css({
            Body: {
                'background-color':'red',
                test0: {
                    'color': 'green'
                },
                test1: {
                    'margin': '500px'
                },
                test2: {
                    'background-color':'blue'
                }
            },
            '#thisStillWorks': {'color': 'blue'}
        })
    )
)

out = page.render()
```
returns (beautified):
```html
<!DOCTYPE HTML>
<html>

<head>
    <style>
        {}
        
        body {
            background-color: red;
        }
        
        #thisStillWorks {
            color: blue;
        }
        
        body a {
            color: green;
        }
        
        body #cool {
            margin: 500px;
        }
        
        body .class1.class3.class2 {
            background-color: blue;
        }
    </style>
</head>

</html>
```
If this is a correct implementation I'll make a pull request, otherwise I'd love to hear what to change.
 
Cheers!
