### ISSUE TITLE
tempy.element.Css - implementation of a update method.

### ISSUE THREAD

**Issue by Hrabal** [Hrabal/TemPy#34]
The Css class accepts a style dict only during init, and can be modified only with the `Teg.attr` method which is not specialized for this class purpose.

It wold be good to have a `Css.update()` (or `Css.add_style()`.. not shure about the name) method than works as a recursive dict update method on the css properties.

**Comment by kinstalinist** [comment]
Can I be assigned this issue? I was actually curious whether I'd be able to put something together so I gave it a shot and I actually have a pull request ready to submit, heh.
