### ISSUE TITLE
CssManager class

### ISSUE THREAD

**Issue by Hrabal** [Hrabal/TemPy#39]
New class: CssManager (or something like that) that extracts common style properties from a formed DOM, creates the Css instance and adds it in the <head>. Extra feature: dumps the css to a versioned file in the static folder and adds a link to this file in the page.

In general, TemPy does not care much about styling, it would be nice to have a dedicated api for css.

**Comment by Purvanshsingh** [comment]
@Hrabal I would like to work on it, can you please brief me about it more?

**Comment by mkhalid-s** [comment]
@Hrabal  My idea, To expose a new Css class. This could create a style tag (<style></style> => Internal styles ) to HTML template. 
Css class could be passed with all the different styling with all the supported tag class we currently have such as "BODY" , "PARA", "HEADER", "HEAD" etc .  What do you think?

**Comment by Hrabal** [comment]
Hi @mkhalid-s , can you provide a mockup example of your idea? Just a few line of code with the ipotethical CssManager api calls and the expected result?
Thank!

**Comment by mkhalid-s** [comment]
@Hrabal  Sorry for taking so long was a lil busy.

Hypothetical "Sample":

Input:

```
body_dict = {"margin-top":"30px" , "padding":"10px", "background-color":"powderblue"}
h1_dict = {"color":"red" , "height":"55px"}
css = CssManager().add("body", body_dict).add("h1", h1_dict)
```

Output:


```
<style>
body {
  background-color: powderblue;
  margin-top: 30px;
  padding: 10px;
}
h1 {
  color: blue;
  height: 55px;
}

</style>
```

**Comment by Hrabal** [comment]
@mkhalid-s sorry too for late response, work is a lot lately :)

Anyway, I like that api, I'd just add an explicit method to produce the style tag, like so:

    manager = CssManager().add("body", body_dict).add("h1", h1_dict)
    manager.render()   # <- this produces the string

 Please go on and work on that if you are still interested.

My original idea was to make CssManager a bit dynamic, and your api is a good start. That's what I had in mind: if added to a Html or Head tag, il would add the style to the page, and if added to other tags it would add style property on the html tag, something on those lines:

    # bind to "page"
    manager = CssManager().add("h1", {"color": "goldenrod"})
    Html().bind_css(manager).render()
    >>> <html><head><style>h1 { color: goldenrod; } </style></head></html>

    # bid to "normal" tag
    manager = CssManager().add("h1", {"color": "goldenrod"})
    H1().bind_css(manager).render()
    >>> <h1 style="color: goldenrod"><\h1>
    H2().bind_css(manager).render()
    >>> <h2><\h2>   # <- no style applied for manager does not contain a rule for h1
