### ISSUE TITLE
Implementation of a .find method to search for things in the tree.

### ISSUE THREAD

**Issue by Hrabal** [Hrabal/TemPy#40]
It would be nice to have a `tempy.DOMElement.find()` method that traverse the tree starting from the element on which is called and accepts:

- css selectors -> and returns the matching elements
- TemPy classes -> and returns all the instances of this class
- names -> and returns all the elements that are attributes of some `DOMElement` with that name

I'm thinking a signature like this one:

    def find(css_string_or_class_name, names=list_of_strings)

**Comment by RahulTirumalareddy** [comment]
Hi, can I be assigned to this issue? I just stumbled upon this project today, but it seems interesting so I'd like to help contribute.

**Comment by Hrabal** [comment]
Hi @RahulTirumalareddy, are you still interested on this issue?

**Comment by nadaj** [comment]
I would like to work on this issue, can you give an example for the method calls?
My questions are:

1. For the css selectors, I thought you might think of the way it was resolved in issue #44, having them in a list. And by that did you consider searching the css attrs? 
2. Are names a list of class names or classes?
3. You can pass either the css_string_or_class_name or the names?

**Comment by Hrabal** [comment]
Hey, no problem, take the issue but please make a separate dev branch for that.

Answers:
- 2. `names` is a list of attribute names, this is useful only for recursive search.
- 3. Yes, my example signature is wrong but both the parameters are optional. The idea is that `css_string_or_class_name` will work as a filter on HTML-linkable attributes while `names` will work on the TemPy-ish node name attribute on the father. So the following code would work:
```
from tempy.tags import A, Div, Pre, Br
tag = Div()(A(),A(),Pre(),Br(),foo=Br())
tag.find()   # will return a generator yielding all the children -> (A(),A(),Pre(),Br(),Br())
tag.find(names='foo')   # will return a generator yielding all the children named foo -> (Br())
tag.find(A)   # will return a generator yielding all the children instances of A -> (A(),A())
tag.find('Pre')   # will return a generator yielding all the children instances of Pre -> (Pre())
tag.find('Br', names='foo')   # will return a generator yielding all the children instances of Br, named foo -> (Br())
```
- 1. my original idea was to accept JQuery-sh selectors, strings like '#foo .bar, baz', 'baz, bar' etc,  (parsing strings into css selectors is probably re-inventing the wheel, pretty sure it's been done before), but for start we can make the method to accept a list of strings, and later expand the behaviour with css selectors in string format, something like:

```
def find(self, *args, **kwargs):
    if not args or len(args) > 1:
        raise ArgumentErrorOrSomething
    if not isinstance(args[0], Iterable):
        raise NotYetImplementedError
    .....

**Comment by nadaj** [comment]
So for both arguments you have to recursively search the children, not only including direct children I suppose? Like here:
```
tag = Div()(A(),A(),Pre(),Br(),foo=Br(), Div()(A())
tag.find(A) 
```
This will return ```[A(), A(), A()]``` where the last ```A``` is from the last ```Div``` child?

But for the names then, shouldn't the class ```CSS``` have it's own find? Since in ```DOMElement``` the names are being searched thru the children's property ```_name```?

**Comment by Hrabal** [comment]
- yes, just like javascript's css selectors.
- yes, find in `CSS` and find in `DOMElement` are two different implementations with different purposes and behaviors: `CSS.find` looks for css elements inside a "css tree", while the new `DOMElement.find` will use pseudo-css selectors and compare them to actual DOM elements.
