### ISSUE TITLE
TempyTable widget formatting and styling api.

### ISSUE THREAD

**Issue by Hrabal** [Hrabal/TemPy#41]
Right now is not easy to assign css classes and/or apply formatting to TempyTable rows and, cols. After the table creation the user if forced to manually assign classes to each row and/or cell.

For instance, if I want to use bootstrap styling on some rows of a TemPy table I'm forced to access each row and add the needed class. 

If I want to add a `th` with the `scope` attribute to every row I'm forced to iterate over each row.

If I want to apply a formatting to a column after the table creation (say apply a lambda to each cell of a column that formats a date) I'm forced to iterate over the table and manually apply the formatting function.

It would be nice to have a dedicated api for that purpose, some ideas are:

- `map_col(function, column_index)` -> applies `function` to each element in the column
- `map_row(function, row_index)` -> applies `function` to each element in the row
- `make_scope(cols=list_of_cols, rows=list_of_rows)` -> transforms the `Td` tag into a `Th` and adds the correct `scope` attribute
- `col_class(css_class, col_index)` -> adds the css class to each cell in the column
- `row_class(css_class, row_index)` -> adds the `css_class` to the row

**Comment by nadaj** [comment]
If I understood this correctly, this would require creating a new class for Table inside tags.py?

**Comment by Hrabal** [comment]
I was thinking adding those new methods to widgets.py/TempyTable class. I'd rather keep the tags base classes (in tags.py) clean.

**Comment by nadaj** [comment]
I understand. I'd like to add these methods/fix this "issue".

**Comment by Hrabal** [comment]
Sure!

**Comment by Hrabal** [comment]
Solved with https://github.com/Hrabal/TemPy/pull/51
