### ISSUE TITLE
Fix TempyPage title and doctype in init

### ISSUE THREAD

**Issue by Hrabal** [Hrabal/TemPy#42]
The TempyPage widget have a `title` keyword argument that is not used, it should be used to set the page's title.

The TempyPage widget have a `doctype` keyword argument that is not used, it should be used to set the page's doctype.

**Comment by adnanhb** [comment]
I would like to fix this issue. Please assign this to me.

**Comment by Hrabal** [comment]
Hey @adnanhb, are you still interested in this issue?

**Comment by MegaWale** [comment]
Hey @Hrabal, noob pythonian here. i would to contribute to this project, starting with this issue. can i be assigned?? thanks

**Comment by Hrabal** [comment]
Hi @MegaWale , I added you as a collaborator of this repo so you can assign this issue to yourself.
Let me know if you need help/infos on the issue or the code, I just realized the issue text is maybe a little... hem.. "concise"  😄

**Comment by MegaWale** [comment]
thanks hrabel. let me get fixing then :ok_hand:
