### ISSUE TITLE
Css class - extension of the current api

### ISSUE THREAD

**Issue by Hrabal** [Hrabal/TemPy#44]
Linked to https://github.com/Hrabal/TemPy/issues/34, it' would be good to add some extra api to the `tempy.elements.Css`.

I was thinking  of a few methods:
- `replace(element, new_style) `: searches for element in  `css_attrs` and replaces his style dict with the new_style dict (i.e: a new init)
- `clear(*elements)`: removes the style of the given elements (full depth search of the element) , if no arg is given clears the whole css_attrs dict.

**Comment by nadaj** [comment]
I would like to start working on this issue. My question is how to you consider this example:
```
Css({'#id_ex': {
            'color': 'red',
            'div': {
                'color': 'green',
                'border': '1px'
             }
        },
        '#myid': {'color': 'blue'},
        'div': {'color: 'black'}
 })
```
I suppose that the element in the argument of the replace method is a str. If I provide as element='div', should it replace the last div. If the argument was '#id_ex div', it will replace that div inside #id_ex.

**Comment by Hrabal** [comment]
This issue is related to https://github.com/Hrabal/TemPy/issues/33 and (forward-ly looking) to https://github.com/Hrabal/TemPy/issues/40 .

Looking at https://github.com/Hrabal/TemPy/issues/33 , I'd already make this issue to consider TemPy tags (classes or instances) as valid keys for the css div. So all those are valid calls: `Css().replace('div', my_style_dict})`,  `Css().replace(Div, my_style_dict})` and `Css().replace(my_div_instance, my_style_dict})`.

Regarding the matching logic, I'd keep it simple for now and delegate to https://github.com/Hrabal/TemPy/issues/40 a more precise selector matching.

For now I'd apply the `replace` to the elements at the root of the css dict only (making this explicit in docstring), this way I think is more forward-compatible.

This can be a lot of work for the user (it's forced to copy and modify the dict beforehand) but it will be easier to make a backward compatible "css selector finder" class that will traverse the style dict.

To compensate the extra work for the user maybe it's good to add an argument to the `replace` method: `replace(element, new_style, key=None)`, so when a key is explicitly given the method will work on this value only, so the above examples would become:
So:
- an user that want to replace the color attr in "#id_ex div" will call
``` 
Css().replace('#id_ex', {
        'color': 'new_color',
        'border': '1px'
    }, key='div')
```
- an user that want to replace the color attr in  "#id_ex"  will call
``` 
Css().replace('#id_ex', 'new_color', key='color')
```

What you think?

**Comment by nadaj** [comment]
And if you were to have this case:

```
{'html': {
            'body': {
                'color': 'red',
                Div: {
                    'color': 'green',
                    'border': '1px'
                },
               link: {'color': 'yellow'}
            }
        },
        '#myid': {'color': 'blue'}
    }
}
```

If I would want to change the inner Div color to grey, how would the method call for replace look like following your example of the method signature?

**Comment by Hrabal** [comment]
It would be something like this:
```
Css().replace('html', {
    'color': 'red',
        Div: {
            'color': 'green',
            'border': '1px'
        },
        link: {'color': 'grey'}
    }, key='body'
```
Which is ugly and counterintuitive. Any better idea?
Maybe the key argument can be a list of keys, i.e. a path?
```
Css().replace('html', 'grey', key=['body', Div, 'color'])
```

**Comment by nadaj** [comment]
Honestly, it looks a bit simpler to have a replace method signature like this:

```
css.replace_element(['html', 'body', Div, 'color'], 'grey')
```

which puts the whole path inside the first argument as a list. My second choice would be the option you have mentioned with the key argument.

**Comment by Hrabal** [comment]
Yes it makes more sense to put the where in a single argument and the what in another..

This can be the same signature for another `add` (or something like that) method.. `replace` throwing a KeyError if the path does not corresponds to an existing path,  `add` will create keys it they are non-existent..

**Comment by Hrabal** [comment]
closed by https://github.com/Hrabal/TemPy/pull/52
