### ISSUE TITLE
Fix examples import

### ISSUE THREAD

**Issue by nadaj** [Hrabal/TemPy#49]
When checking out the examples, I found that the Import Error pops up since the import isn't valid (e.g. ImportError: cannot import name 'Html'). As shown on the website https://hrabal.github.io/TemPy/usage/, in each example it should be

 from tempy.tags import *

When I changed the imports to this line, it worked as promised. If this is the case, I would like to update the examples.

*also file sw-people.json should be added in order for star_wars file to work

**Comment by Hrabal** [comment]
Hi @nadaj , thanks for opening this. I added you as a collaborator so you can assign yourself this issue.

The examples folder has been abandoned a while ago, I started writing examples then forgot. I'll search for the sw json file.

I've made [this](https://github.com/Hrabal/TemPy/issues/17 ) to add more examples, but it's not a very crowded issue..
