### ISSUE TITLE
redo docs website

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [Hrabal/TemPy#60]
1) the website's code snippets can be more beautiful
2) pulldown menus can be enhanced, somewhat confusing as they are now
3) an overall cleaner look needed

**Comment by SupaFresh** [comment]
Can I work on this?

**Comment by Hrabal** [comment]
Hi @SupaFresh, sure!
Feel free to change the layout/theme etc, and if you have more contents to add be my guest! ;)

Please make a dev branch out of the gh-pages branch so I can check it out locally before merge.

**Comment by Hrabal** [comment]
If anyone is interested in working on this please work on the "gh-pages_REFACTOR" branch I made.

**Comment by Hrabal** [comment]
Kinda solved #2, but I'm not a css ninja so if someone wants to improve the menus, be my guest.

**Comment by Hrabal** [comment]
Added a tutorial, modified the menu (still, if someone can make a better css please do!).
