### ISSUE TITLE
Cleaning up dirt in tempy.tags

### ISSUE THREAD

**Issue by Hrabal** [Hrabal/TemPy#66]
After the `from tempy.tags import *` statement the importing namespace is polluted by some internal TemPy variables that should not be used by the user:

```
>>> from tempy.tags import *
>>> dir()
[.....  'tag', 'tag_cls', 'tag_cls_name', 'tag_parent_cls', 'tags']
```

Those 5 variables should be deleted at the end of the `tags.py` file.

**Comment by mbuccat** [comment]
Hello!

I'd like to help with this

**Comment by Hrabal** [comment]
Hi @mbuccat, thanks for helping! Just submit a PR with your changes and ff you have any question please write in this issue.
