### ISSUE TITLE
Add exception when inserting something in a voidtag

### ISSUE THREAD

**Issue by Hrabal** [Hrabal/TemPy#73]
Right now is possible to put objects or tags inside void tags, which is illegal in html.

This html is invalid: `<br><div></div></br>`, but TemPy let the user do the equivalent with tempy tags:  `Br()(Div())` is completely accepted.

Void tags (denoted by the `_void` class attribute set to `True`) should raise an exception if the user try to add content inside them.

**Comment by kika115** [comment]
Is this issue open??

**Comment by Hrabal** [comment]
Hi @kika115 , no this is not open, I forgot to close the issue.
