### ISSUE TITLE
implement a ".join(*args)" method

### ISSUE THREAD

**Issue by Hrabal** [Hrabal/TemPy#75]
It would be nice to have a `DOMElement.join()` method that mimics the `str.join()` method in python.

Ideally, this method would accept a list of things and returns the passed list with the chosen TemPy tag instances between the list elements just like the `str.join` method:

    Br.join(["pizza", "pasta", "lasagna"])
    >>> ["pizza", Br(), "pasta", Br(), "lasagna"]

    Hr.join(["pizza", "pasta", "lasagna"])
    >>> ["pizza", Hr(), "pasta", Hr(), "lasagna"]

    Br.join(["pizza"])
    >>> ["pizza"]

I'd make it a classmethod, so both `Br.join(["pizza", "pasta", "lasagna"])` and `Br().join(["pizza", "pasta", "lasagna"])` sytntaxes are allowed.
In the latter syntax copies of `Br()` have to be created.

**Comment by Navneet78** [comment]
Hey I want to do this

**Comment by Hrabal** [comment]
Hi @Navneet78 thanks for taking this. I assigned you this issue. 
If you have any question just ask on this issue.

**Comment by Navneet78** [comment]
Hello @Hrabal What I am working on this issue and I am creating a class method in DOMelement class. which takes a list of elements as input and return a list. And that list having consecutive previous elements and that class instance. Am I right like in above example Hr is instance of DOMelement class and it's coming between any two elements of given list. Am I right ?
And also  do I need to write unit-test for this in tests?

**Comment by Hrabal** [comment]
Hi @Navneet78 

>  Am I right like in above example Hr is instance of DOMelement class and it's coming between any two elements of given list.

Yes, Hr is an instance of Hr class, which is a subclass of DOMelement. The method should return an iterator containing the input iterator with instances of the called class in between each two elements. So, for exampe, calling 'join' on Hr will make Hr's and calling 'join' on Div will make Div's instances.

> And also do I need to write unit-test for this in tests?
Yes please

**Comment by Navneet78** [comment]
hey, I have little confusion in a class method we are not passing instance of class as parameter. in classmethod we are just passing cls parameter instead of self (which points to instance of object) parameter and cls parameter which points to class not instance of class. So in order to pass instance of object to classmethod we need to specify function like this

> Hr.join(["pizza", "pasta", "lasagna"], Hr)
> '>>>'["pizza", <__main__.Hr 55664848.>, "pasta", <__main__.Hr 55664848.>, "lasagna"]

without passing instance of class we will get it like this
> Hr.join(["pizza", "pasta", "lasagna"], Hr)
> '>>>'["pizza", <__main__.Hr .>, "pasta", <__main__.Hr .>, "lasagna"]

I hope you got the difference. Please help what should I do?

**Comment by Hrabal** [comment]
Hey,
when defining a classmethod the signature changes from "self" (which points to the instance of the class) to "cls" (usually), which is the class itself. So, to have instances we can just instantiate the cls parameter directly:

    class A:
        @classmethod
        def c_method(cls, val):
            return cls(), val

    print(A.c_method("foo"))
    >>> (<__main__.A instance at 0x109e01998>, 'foo')
    print(A().c_method("foo"))
    >>> (<__main__.A instance at 0x109e01998>, 'foo')

**Comment by Navneet78** [comment]
Hello, I think by using 'cls()' first you are creating a new object of class and returning it. It's not same instance as that we used to call that method. For instantiating an object we need parameters of init method and unlike 'self', cls don't have access to instance argument.
> ```
> class A:
>     def __init__(self, arg):
>          self.ins_arg=arg
>     @classmethod
>     def c_method(cls, val):
>         return cls(), val
> 
> print(A('arg').c_method("foo"))
> >>> TypeError: __init__() missing 1 required positional argument: 'arg'
> ```
so please help !

**Comment by Hrabal** [comment]
Hi,

> I think by using 'cls()' first you are creating a new object of class and returning it. 

Yes, this is ok to happen, we don't want the same instance in between the elements of the input, but several new instances of the same class.

> For instantiating an object we need parameters of init method

it's ok to just init the class with no parameters ( `cls()` ).
