### ISSUE TITLE
Implement "DOMElementmap()" method

### ISSUE THREAD

**Issue by Hrabal** [Hrabal/TemPy#76]
It would be nice to have a DOMElement.map(list_of_things) method that creates a list of elements containing the passed elements in the list.

    Td.map(["pizza", "pasta", "lasagna"])

will produces the equivalent of:

    [Td()(thing) for thing in ["pizza", "pasta", "lasagna"]]

I'd make it a classmethod, so both `Td.map(["pizza", "pasta", "lasagna"])` and `Td().map(["pizza", "pasta", "lasagna"])` sytntaxes are allowed.
In the latter syntax copies of Td() have to be created.

**Comment by udoedo** [comment]
Hi, I would like to contribute to this issue. But, can you be more specific about what do you expect to get on the output ?

**Comment by Hrabal** [comment]
Hi @udoedo, thanks for the help! I'm assigning you the issue.

I'm expecting as output a generator that yields instances (copies) of the tag on which .map is called, with already inserted in them each element of the inpust iterable.
So, given this input: 

    Td.map(["pizza", "pasta", "lasagna"])

the output should be a interator of the elements of this list:

    [Td()("pizza"), Td()("pasta"), Td()("lasagna")]

**Comment by Navneet78** [comment]
Let's do this too.

**Comment by Hrabal** [comment]
Hey @Navneet78, someone else asked to work in this issue before, so I assigned this to @udoedo.
I see he didn't fork the repo so maybe he's not working on this one... I'll wait few days and if udoedo did not confirm I'll assign this to you.

**Comment by Navneet78** [comment]
Hi @Hrabal please review #81 and close the issue

**Comment by Hrabal** [comment]
@udoedo not responding, #81 merged, thanks @Navneet78
