### ISSUE TITLE
TODO: Wrapping into multiple containers

### ISSUE THREAD

**Issue by Hrabal** [Hrabal/TemPy#9]
`DOMElement.wrap` now accepts a single `DOMElement` instance and wraps `self` into this other instance.

Method signature should change to accept a iterable as first argument or multiple (single or iterable) arguments. `self` (copies of) will be wrapped inside each given element, i.e:
    
    some_divs = [Div() for _ in range(10)]
    to_be_wrapped = Span()
    to_be_wrapped.wrap(some_divs, P(), A(), (Pre() for _ in range(10)))

wrap will add `to_be_wrapped` into each div in `some_divs`, and into each `DOMElement` found in args.

Extra implementation:
add kwargs in signature so wrapping will perform a named insertion.

https://codeclimate.com/github/Hrabal/TemPy/tempy/tempy.py#issue_59a0588692503c0001000033

**Comment by amathael** [comment]
I'm new to GitHub really, so maybe if it is `up-for-grab`, can I try to work on it?

**Comment by Hrabal** [comment]
Hi @amathael , yeah this issue is not difficult to solve.

The method that should be changed is `tempy.DOMElemet.wrap()`, it now accepts only 1 argument, it should accept a variable number of arguments (see [here if you never used argument unpacking](https://docs.python.org/dev/tutorial/controlflow.html#arbitrary-argument-lists) ) check that every argument is a `tempy.DOMElement` instance and apply the current wrap code for each argument, cloning `self`.

If you want to try just [fork this repository](https://help.github.com/articles/fork-a-repo/), develop the feature (please add tests, If you'r not familiar with Python's unittest framework just ask me ;) ) and [make a Pull Request](https://help.github.com/articles/about-pull-requests/)

**Comment by amathael** [comment]
Great, thank you!

**Comment by amathael** [comment]
And into which branch should I commit my changes? I need to make a commit and push before creating a Pull Request, right? Or it's easier than I think? :\

**Comment by Hrabal** [comment]
If you fork the repository you'll have a github.com/amathael/TemPy repository and you can commit/push your changes into the master branch of your fork.

Later, when finished, you have to make a Pull Request starting from the master branch of your repo to the master branch of the main repo.
