### ISSUE TITLE
Automatic HTML entities / escaping of strings?

### ISSUE THREAD

**Issue by cluelessperson** [Hrabal/TemPy#94]
I'm trying to pass a string that contains another HTML element... 

How do I get around the html string escaping?

**Comment by Hrabal** [comment]
Hi,
if I get your problem right you have two ways of doing it:

1) Insert the html string in the page using the Escape object:

    from tempy.tags import Div
    from tempy import Escaped
    print(Div()(
        Escaped("<span>old HTML</span>")
    ).render())

    >>> <div><span>old HTML</span></div>

2) Parsing the string into TemPy objects, if you need to modify the string's content:

    from tempy.tags import Div
    from tempy import T
    
    string_with_html = "<span>old HTML</span>"
    
    
    tempy_version_of_the_string = T.from_string(string_with_html)
    print(tempy_version_of_the_string)
    >>> [<tempy.tags.Span 119680685800612761519806559943057081345. 1 childs.>]

    tempy_version_of_the_string[0](' some other content')
    
    print(Div()(
        tempy_version_of_the_string
    ).render())
    >>> <div><span>old HTML some other content</span></div>

**Comment by cluelessperson** [comment]
Hi there, I discovered it was acceptable to split my string into parts.

```
a = ['ABC', Span(klass="user_mention")("username"), 'DEF']
b = Div(*a) 
b.render()
```

But thank you. :)
