### ISSUE TITLE
Xss filters

### ISSUE THREAD

**Issue by codingsett** [Hrabal/TemPy#97]
Hello, just came across this nice project and was wondering if it has inbuilt xss filters...i saw there is an an escape function but was not sure if it filters xss attacks like jinja2

**Comment by Hrabal** [comment]
Hi @codingsett , sorry for late reply.
Output is produced though the `DOMElement._iter_child_renders` method, that apply Python's stdlib `html.escape` function to every encountered string. So yes, Xss is prevented by default.

The `tempy.Escaped` class can be used to explicitly bypass this behavior. This class should be used carefully for it can lead to xss injections:

```
>>> import tempy
>>> from tempy.tags import Div
>>> from tempy import Escaped
>>> # normal xss filtered behaviour
>>> Div()("some malicious <script src='http://123.342.74.2/xss.js'> user imput").render()
'<div>some malicious &lt;script src=&#x27;http://123.342.74.2/xss.js&#x27;&gt; user imput</div>'
>>>
>>> # escaped version
>>> Div()(Escaped("some malicious <script src='http://123.342.74.2/xss.js'> user imput")).render()
"<div>some malicious <script src='http://123.342.74.2/xss.js'> user imput</div>"
```
