### ISSUE TITLE
Fix PEP8 linting errors

### ISSUE THREAD

**Issue by jamiemott** [Hrabal/TemPy#98]
I am in an open source class and as part of that we had to do some testing on a repository.  This project's contributing guide states it uses PEP8/PEP20, but I found several PEP8 errors (unused variables, accessing protected variables, improper naming of variables, classes, functions, etc.).  I would like to fix those errors.  Thanks!

**Comment by jamiemott** [comment]
May I please be assigned to this issue?  Thanks!

**Comment by Hrabal** [comment]
Hi @jamiemott sure, any help is appreciated! I'll wait for yout PR.

**Comment by Hrabal** [comment]
Fixed with PR #100
